import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import {readApiResponse} from './api.js';
const examples=[['Standard return','MX-1001','adebayo.ogunleye@example.com','Changed my mind, want a refund'],['Final sale','MX-1002','folake.adeyemi@example.com','Refund the sneakers'],['Human review','MX-1004','yetunde.ajayi@example.com','Refund the laptop'],['Damaged item','MX-1005','olumide.akinwale@example.com','Speaker arrived damaged'],['Mixed basket','MX-1009','temitope.olaniyan@example.com','Refund the whole order']];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const date=s=>new Date(s).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const verdict=r=>r.final_verdict||r.verdict;
function Badge({value}){return <span className={'badge '+value}><span aria-hidden="true">{value==='Approved'?'✓':value==='Denied'?'×':'◷'}</span>{value}</span>;}
function App(){
 const [page,setPage]=useState('customer'),[email,setEmail]=useState(''),[orderId,setOrder]=useState(''),[message,setMessage]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState('connecting'),[token,setToken]=useState(''),[rows,setRows]=useState([]),[stats,setStats]=useState(null),[selected,setSelected]=useState(null),[logs,setLogs]=useState([]),[note,setNote]=useState(''),[filter,setFilter]=useState('All'),[search,setSearch]=useState(''),[loaded,setLoaded]=useState(false),[updated,setUpdated]=useState(null),[auditBusy,setAuditBusy]=useState(false);
 const [requestKey,setRequestKey]=useState(crypto.randomUUID());
 const selection=useRef(0), workspace=useRef(0);
 async function api(path,options={}){const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});return readApiResponse(r);}
 useEffect(()=>{api('/health').then(d=>setMode(d.aiMode)).catch(()=>setMode('unavailable'));},[]);
 async function refresh(){const generation=workspace.current;const [list,counts]=await Promise.all([api('/admin/refunds'),api('/admin/refunds/stats')]);if(generation!==workspace.current)return;setRows(list);setStats(counts);setLoaded(true);setUpdated(new Date());}
 useEffect(()=>{if(page!=='support'||!loaded||!token)return;const timer=setInterval(()=>{refresh().catch(e=>setError(e.message));},30000);return()=>clearInterval(timer);},[page,loaded,token]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');setResult(null);try{setResult(await api('/refunds',{method:'POST',body:JSON.stringify({email,orderId,message,idempotencyKey:requestKey})}));setRequestKey(crypto.randomUUID());if(loaded)await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function load(){setBusy(true);setError('');try{await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function inspect(r){const id=++selection.current;setSelected(r);setNote('');setLogs([]);setAuditBusy(true);try{const data=await api(`/admin/refunds/${r.id}/audit`);if(id===selection.current)setLogs(data);}catch(e){if(id===selection.current)setError(e.message);}finally{if(id===selection.current)setAuditBusy(false);}}
 async function resolve(value){setBusy(true);setError('');try{const r=await api(`/admin/refunds/${selected.id}/resolve`,{method:'POST',body:JSON.stringify({verdict:value,note})});await inspect(r);await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const change=fn=>e=>{fn(e.target.value);setRequestKey(crypto.randomUUID());setResult(null);};
 function changeToken(value){workspace.current++;selection.current++;setToken(value);setLoaded(false);setStats(null);setRows([]);setSelected(null);setLogs([]);setUpdated(null);}
 function navigate(value){setPage(value);setError('');if(value==='support'&&loaded)load();}
 const visible=rows.filter(r=>(filter==='All'||verdict(r)===filter)&&`${r.order_id} ${r.customer_email} ${r.id}`.toLowerCase().includes(search.toLowerCase()));
 const metrics=[['All','Total requests','All stored requests','↗','total'],['Approved','Approved','Including staff approvals','✓','approved'],['Denied','Denied','Including staff denials','×','denied'],['Escalated','Awaiting review','Needs a human decision','◷','escalated']];
 return <div className="app-shell"><header><a className="brand" href="/" aria-label="MartX Care home">mart<span>✳</span><small>CARE</small></a><nav aria-label="Workspace"><button className={page==='customer'?'active':''} onClick={()=>navigate('customer')}>Customer care</button><button className={page==='support'?'active':''} onClick={()=>navigate('support')}>Support workspace <span aria-hidden="true">↗</span></button></nav><span className={'status '+mode}><i/>{mode==='openai'?'AI configured':mode==='offline'?'Demo mode':mode==='connecting'?'Connecting':'Service unavailable'}</span></header><main className={page}>
 {page==='customer'?<><section className="hero"><div><div className="eyebrow"><span/> CUSTOMER CARE, WITH CLARITY</div><h1>A better way<br/>to make it <em>right.</em></h1><p className="intro">A change of plans. An unexpected delivery.<br/>Whatever happened, let’s find your next step.</p><div className="hero-tags"><span>✓ Clear refund policy</span><span>✓ Human help when needed</span></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-label">A LITTLE CARE GOES A LONG WAY</div><div className="parcel"><span>mart✳</span><div className="parcel-tape"/></div><div className="floating-check">✓</div><div className="art-caption"><span>↩</span><div>Better outcomes.<small>One request at a time.</small></div></div></div></section>
 <div className="layout"><section className="card request-card"><div className="cardhead"><span className="icon">↩</span><div><h2>Tell us about your order</h2><p>We’ll check the details and explain the decision.</p></div><span className="step">01 — REQUEST</span></div><form onSubmit={submit}><div className="fields"><label>Email address<input type="email" required value={email} onChange={change(setEmail)} placeholder="you@example.com" autoComplete="email"/></label><label>Order number<input required pattern="MX-[0-9]{4,10}" value={orderId} onChange={change(setOrder)} placeholder="MX-1001"/><span className="field-hint">You’ll find this in your order confirmation.</span></label></div><label>How can we help?<textarea required minLength={5} maxLength={2000} value={message} onChange={change(setMessage)} placeholder="Tell us what happened and why you’d like a refund…"/></label><div className="formfoot"><span>{message.length.toLocaleString()} / 2,000 characters</span><button className="primary" disabled={busy}>{busy?'Checking your request…':'Check my refund'} <span aria-hidden="true">→</span></button></div><p className="form-note">Demo experience · No real payments are issued.</p></form>{error&&<p role="alert" className="error">{error}</p>}{result&&<div role="status" className={'response '+result.verdict}><Badge value={result.verdict}/><h2>{result.refundAmount>0?money(result.refundAmount):'Your request has been reviewed'}</h2><p>{result.reply}</p><small>Policy {result.ruleIds.join(', ')} · {result.aiMode==='openai'?'AI-assisted':'Offline / fallback'}<br/>Reference {result.id}</small></div>}</section>
 <aside><div className="promise"><div className="eyebrow">THE POLICY, SIMPLIFIED</div><h2>Clear rules.<br/>No guesswork.</h2><ul><li><span className="policy-number">01</span><div><b>30 days to return</b><p>From delivery, including day 30.</p></div></li><li><span className="policy-number">02</span><div><b>Eligible items count</b><p>Final-sale items are excluded.</p></div></li><li><span className="policy-number">03</span><div><b>A person when it matters</b><p>Refunds above $500 go to review.</p></div></li></ul></div><div className="demo"><div className="demo-title"><span>✧</span><b>Take it for a test drive</b></div><p>Fill the form with a sample order.</p><div className="chips">{examples.map(x=><button key={x[1]} onClick={()=>{setOrder(x[1]);setEmail(x[2]);setMessage(x[3]);setResult(null);setError('');setRequestKey(crypto.randomUUID());}}>{x[0]} <span>↗</span></button>)}</div></div></aside></div></>:
 <><section className="dashboard-heading"><div><div className="eyebrow">SUPPORT WORKSPACE</div><h1>Every request.<br className="mobile-break"/> <em>A clear next step.</em></h1><p className="intro">The full picture, from first request to final resolution.</p></div><div className="workspace-label"><span className="live-dot"/> {loaded?'Workspace connected':'Secure workspace'}</div></section>
 <section className="access card"><div className="access-heading"><span className="icon">⌘</span><div><h2>{loaded?'You’re connected':'Open your workspace'}</h2><p>{loaded?'Totals refresh every 30 seconds.':'Enter your support token to view customer requests.'}</p></div></div><label><span className="sr-only">Support access token</span><input type="password" autoComplete="off" value={token} onChange={e=>changeToken(e.target.value)} placeholder="Support access token"/></label><button className="primary" disabled={busy||!token} onClick={load}>{busy?'Loading…':loaded?'Refresh ↻':'Connect →'}</button></section>
 {error&&<p role="alert" className="error">{error}</p>}<div className="section-caption"><span>WORKSPACE OVERVIEW</span><span>{updated?`Updated ${updated.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})} · All-time totals`:'Connect to see database totals'}</span></div><div className="metrics">{metrics.map(([value,label,caption,symbol,key])=><button aria-pressed={filter===value} className={`metric ${value} ${filter===value?'chosen':''}`} onClick={()=>setFilter(value)} key={value}><div className="metric-top"><span>{label}</span><span className="metric-symbol" aria-hidden="true">{symbol}</span></div><strong>{stats?stats[key].toLocaleString():'—'}</strong><small>{caption}</small></button>)}</div>
 <div className="supportgrid"><section className="card requests"><div className="panel-heading"><div><h2>Request activity</h2><p>Latest 100 requests · Select an order to review</p></div><span className="count-pill">{loaded?rows.length:'—'}</span></div><div className="table-tools"><label className="search"><span aria-hidden="true">⌕</span><input aria-label="Search recent requests" placeholder="Search order, email or reference…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter decisions" value={filter} onChange={e=>setFilter(e.target.value)}><option value="All">All decisions</option><option>Approved</option><option>Denied</option><option value="Escalated">Awaiting review</option></select></div>{!visible.length?<div className="empty"><span className="empty-icon">≡</span><h3>{!loaded?'Your workspace awaits':rows.length?'No matching requests':'A clean slate'}</h3><p>{!loaded?'Connect with your support token to see activity and decisions.':rows.length?'Try a different search or decision filter.':'Customer requests will appear here when submitted.'}</p></div>:<div className="tablewrap"><table><thead><tr><th>Order / customer</th><th>Decision</th><th>Amount</th><th>Received</th></tr></thead><tbody>{visible.map(r=><tr className={selected?.id===r.id?'selected-row':''} key={r.id}><td><button disabled={busy} className="orderlink" onClick={()=>inspect(r)}>{r.order_id} <span>↗</span></button><small>{r.customer_email}</small></td><td><Badge value={verdict(r)}/><small>{r.review_status==='resolved'?'Reviewed by support':r.review_status==='pending'?'Needs review':'Automatic decision'}</small></td><td className="amount">{money(verdict(r)==='Denied'?0:r.refund_amount)}</td><td className="date">{date(r.created_at)}</td></tr>)}</tbody></table></div>}<div className="table-footer">{visible.length} shown in recent activity<span>Totals above include the entire database.</span></div></section>
 <section className="card detail"><div className="panel-heading"><div><div className="eyebrow">THE DETAILS</div><h2>Decision trail</h2></div><span className="icon">≋</span></div>{!selected?<div className="empty detail-empty"><span className="empty-icon">↖</span><h3>Follow the story</h3><p>Select a request to see the customer’s message, policy checks, and review history.</p></div>:<><div className="detail-order"><h3>{selected.order_id}</h3><Badge value={verdict(selected)}/></div><p className="customer-email">{selected.customer_email}</p><div className="eyebrow muted">CUSTOMER MESSAGE</div><blockquote>{selected.raw_message}</blockquote>{selected.final_verdict?<div className="resolution-summary"><b>Resolved · {selected.final_verdict}</b><p>{selected.resolution_note}</p></div>:<p className="initial-reply">{selected.customer_reply}</p>}{auditBusy?<p role="status">Loading decision trail…</p>:<div className="timeline">{logs.map(l=><div className="log" key={l.id}><div className="log-heading"><b>{l.step==='classification'?'Message assessment':l.step==='policy'?'Policy decision':'Support resolution'}</b><small>{date(l.created_at)}</small></div>{l.step==='policy'?<><p>{l.payload.notes.join(' ')}</p><div className="rule-tags">{l.payload.rules.map(r=><span key={r}>{r}</span>)}</div></>:l.step==='classification'?<><p>{l.payload.mode==='skipped'?'Ownership could not be verified.':`${l.payload.reason||'Unclear'} intent · ${Math.round((l.payload.confidence||0)*100)}% confidence`}</p><small>{l.payload.mode} classification{l.payload.injection?' · Manipulation flagged':''}{l.payload.ambiguous?' · Clarification needed':''}</small></>:<p>{l.payload.verdict} · {l.payload.note}</p>}</div>)}</div>}{selected.review_status==='pending'&&<div className="review-form"><label>Review note<textarea value={note} onChange={e=>setNote(e.target.value)} minLength={10} maxLength={1000} placeholder="Explain your decision (at least 10 characters)"/></label><div className="actions"><button className="primary" disabled={busy||note.trim().length<10} onClick={()=>resolve('Approved')}>✓ Approve</button><button className="deny-button" disabled={busy||note.trim().length<10} onClick={()=>resolve('Denied')}>Deny</button></div></div>}</>}</section></div></>}
 <footer><a className="footer-brand" href="/">mart✳ care</a><span>A little help. A better outcome.</span><span>Assessment demo · No real payments · Policy v1.0</span></footer></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
